version: '3.1'
networks:
  taxajuros:
      name: taxajuros
services:
  taxajuros:
    image: ensilva/ensilvataxajuros:latest
    ports: 
      - 80:80    
    networks: 
      - taxajuros  
  calculojuros:
    image: ensilva/ensilvacalculojuros:latest
    ports: 
      - 5001:80
    networks:
      - taxajuros
    depends_on:
      - taxajuros
